name: Windows
on:
  - push
  - pull_request
jobs:
  test:
    name: Test
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "2.5"
          - "2.6"
          - "2.7"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Update MSYS2 keyring
        run: |
          # https://www.msys2.org/news/#2020-06-29-new-packagers
          Invoke-WebRequest `
            -Uri https://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz `
            -OutFile msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
          ridk exec pacman `
            --noconfirm `
            --upgrade `
            msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
      - name: Update MSYS2
        run: |
          ridk exec pacman --sync -yy -uu --noconfirm
          taskkill /F /FI "MODULES eq msys-2.0.dll"
      - name: Update GCC
        run: |
          ridk exec pacman --sync --noconfirm mingw-w64-x86_64-gcc
      - name: Install Groonga explicitly
        run: |
          ridk exec pacman --sync --noconfirm mingw-w64-x86_64-groonga
      - name: Install dependencies for building gem
        run: |
          gem install `
            packnga `
            yard
      - name: Build gem
        run: |
          rake build
      - name: Install gem
        run: |
          gem install pkg\*.gem
      - name: Test
        run: |
          $Env:NO_MAKE = "yes"
          ruby test\run-test.rb
